export type AvailableJob = keyof typeof JOB2ICON;

/** Icon map of jobs to their fontawesome5 (free) counterpart. */
export const JOB2ICON = {
  AI: 'eye',
  Ассистент: 'toolbox',
  'Атмосферный техник': 'fan',
  Бармен: 'cocktail',
  'Bit Avatar': 'code',
  Bitrunner: 'gamepad',
  Ботаник: 'seedling',
  Капитан: 'crown',
  'Cargo Gorilla': 'paw',
  Грузчик: 'box',
  'CentCom Commander': 'star',
  'CentCom Head Intern': 'pen-fancy',
  'CentCom Intern': 'pen-alt',
  'CentCom Official': 'medal',
  Священник: 'cross',
  Chef: 'utensils',
  Химик: 'prescription-bottle',
  'Главный инженер': 'user-astronaut',
  'Главный врач': 'user-md',
  Клоун: 'face-grin-tears',
  Повар: 'utensils',
  Патологоанат: 'skull',
  Библиотекарь: 'book',
  'Cyber Police': 'qrcode',
  Cyborg: 'robot',
  Детектив: 'user-secret',
  Генетик: 'dna',
  'Глава персонала': 'dog',
  'Глава службы безопасности': 'user-shield',
  Уборщик: 'soap',
  Адвокат: 'gavel',
  Врач: 'staff-snake',
  Мим: 'comment-slash',
  Парамедик: 'truck-medical',
  'Personal AI': 'mobile-alt',
  Заключенный: 'lock',
  Психолог: 'brain',
  Квартирмейстер: 'sack-dollar',
  'Директор исследований': 'user-graduate',
  Робототехник: 'battery-half',
  Учёный: 'flask',
  'Офицер службы безопасности (Грузы)': 'shield-halved',
  'Офицер службы безопасности (Инженерия)': 'shield-halved',
  'Офицер службы безопасности (Медицина)': 'shield-halved',
  'Офицер службы безопасности (Наука)': 'shield-halved',
  'Офицер службы безопасности': 'shield-halved',
  Шахтёр: 'digging',
  'Станционный инженер': 'gears',
  'Syndicate Operative': 'dragon',
  Вирусолог: 'virus',
  Надзиратель: 'handcuffs',
} as const;
